apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda-app
  template:
    metadata:
      labels:
        app: lambda-app
    spec:
      containers:
      - name: lambda-app
        image: localhost:5000/lambda-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

       
