on:
  push:
    branches:
      - main

      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Lint with Ruff
        run: poetry run ruff check .
        continue-on-error: false
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          poetry run pytest --cov-report term-missing --cov=lambda_app/ tests/
        continue-on-error: false

      
      - name: Build Docker image
        run: docker build -t lambda-app .

      - name : tage Docker image
        run: docker tag lambda-app localhost:5000/lambda-app
        
      - name: Push Docker image
        run: docker tag lambda-app localhost:5000/lambda-app && docker push localhost:5000/lambda-app
    

      - name: Create k3d cluster and deploy
        run: |
          k3d cluster create lambda-cluster --registry-create lambda-cluster:5000 -p 3001:8080@loadbalancer
          k3d image import localhost:5000/lambda-app -c lambda-cluster
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          
      - name: Check Lambda function with curl
        run: |
          sleep 10 
          SERVICE_IP="$(kubectl get svc lambda-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"

          echo "Waiting for service IP..."
          sleep 10

          echo "🌐 Service is ready at $SERVICE_IP:8080"

          curl -d @events/event.json http://$SERVICE_IP:8080/2015-03-31/functions/function/invocations -o response.json

          if grep -q '"statusCode": 200' response.json; then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi
